rails g migration add_columns_to_products brand:string binding:string color:string manufacturer:string model:string upc:string lowest_new_price:float release_date:datetime lowest_used_price:float total_offers:integer more_offers_url:string merchant:string availability:integer super_saver_eligibility:boolean prime_eligibility:boolean similar_products:text

item["ItemAttributes"]["Brand"]
item["ItemAttributes"]["Binding"]
item["ItemAttributes"]["Color"]
item["ItemAttributes"]["Manufacturer"]
item["ItemAttributes"]["Model"]
item["ItemAttributes"]["Upc"]
item["ItemAttributes"]["ReleaseDate"]
item["OfferSummary"]["LowestNewPrice"]
item["OfferSummary"]["LowestUsedPrice"]
item["Offers"]["TotalOffers"]
item["Offers"]["MoreOffersUrl"]
item["Offers"]["Merchant"]
item["Offers"]["OfferListing"]["AvailabilityAttributes"]
item["Offers"]["OfferListing"]["IsEligibleForPrime"]
item["Offers"]["OfferListing"]["IsEligibleForSuperSaverShipping"]
item["SimilarProducts"]["SimilarProduct"]